### ISSUE TITLE
How many GPIOs can I use

### ISSUE THREAD

**Issue by ranhaber** [eadf/esp8266_easygpio#2]
How many GPIOs can I use with the ESP-07 or ESP-12? (not including ADC)
GPIO 15 is tied to ground and GPIO 0 is... well I hope that I can leave it. 
Thanks

**Comment by eadf** [comment]
You can use GPIO[0-5, 9-15]. If you use GPIO1 and GPIO3 you will have to disable uart0 (the console).

This is what i use to disable RXT (and thus free up GPIO3) : [esp8266_stdout.](https://github.com/eadf/esp8266_stdout)

You can use GPIO0, GPIO2 and GPIO15 if you use pullup and pulldown resistors and that the thing you connect each GPIO to is either an input or set to tristate during the bootup process.

GPIO16 is not implemented in easygpio yet but it seems really simple to do once i get the time. (the hardware on GPIO16 does not support interrupts).

GPIO[9-11] are, so far, not accessible on any esp chips.
