### ISSUE TITLE
PIN_PULLDWNs gone from eagle_soc.h in latest esp-open-sdk

### ISSUE THREAD

**Issue by emogg** [eadf/esp8266_easygpio#3]
The title says it all. Any plans to fix it?

**Comment by scargill** [comment]
If I remember righly - there is no pulldown hardware on the current chips - hence in my copy I've deleted in easygpio.c, references to PIN_PULLDWN_DIS but left everything else alone.

**Comment by eadf** [comment]
Sorry for the delay.
I hope my latest commit fixes the issue.
So far I've only tested my changes with SDK 1.5.2
